---
- name: download GPG key
  ansible.builtin.shell: " wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add - "

- name: add grafana repository
  become: true
  ansible.builtin.shell: add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  
- name: install grafana
  become: true
  ansible.builtin.apt:
    name: grafana
    update_cache: yes

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

# - name: "Check if Grafana is accessible."
#   uri:
#     url: http://127.0.0.1:3000
#     method: GET
#     status_code: 200