---
- name: install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  register: nginx_installed

- name: remove default virtual host configuration
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: stop nginx

- name: install certbot
  become: true
  ansible.builtin.apt:
    name: certbot
    state: present

- name: install certbot's nginx plugin
  become: true
  ansible.builtin.apt:
    name: python3-certbot-nginx
    state: present

- name: install test certs
  become: yes
  ansible.builtin.command: "certbot certonly --nginx --test-cert --agree-tos --no-eff-email -q --email {{ email }} -d {{ domain_name }} -d www.{{ domain_name }} -d gitlab.{{ domain_name }} -d grafana.{{ domain_name }} -d prometheus.{{ domain_name }} -d alertmanager.{{ domain_name }}"

- name: create vhost files from template
  become: true
  ansible.builtin.template:
    src: templates/sites.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item.fqdn }}.conf
  with_items: "{{ servers }}"
  notify: reload nginx