---
- name: Start Nginx
  become: true
  service:
    name: nginx
    state: started

- name: Reload Nginx
  become: true
  service:
    name: nginx
    state: reloaded

- name: Restart Nginx
  become: true
  service:
    name: nginx
    state: restarted