version: "3.8"
services:
  postgres:
    container_name: "postgres"
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - vol_1:/var/lib/postgresql/data/
      - vol_2:/var/lib/postgresql/backup/  
    ports: 
      - "5432:5432"
volumes:
  vol_1:
  vol_2: