before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$keypr" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - test
  - deploy

job-test:
  stage: test
  script:
    - echo "gitlab"
    - touch test.txt

job-deploy:
  rules:
  - if: '$CI_COMMIT_TAG != null'

  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@app.homopoluza.ru sudo chown -R ubuntu /var/www/www.homopoluza.ru/wordpress/ 
    - rsync -rvz -e "ssh -o StrictHostKeyChecking=no" ./* ubuntu@app.homopoluza.ru:/var/www/www.homopoluza.ru/wordpress/
    - ssh -o StrictHostKeyChecking=no ubuntu@app.homopoluza.ru mv /var/www/www.homopoluza.ru/wordpress/index.php ./index.php.old
    - ssh -o StrictHostKeyChecking=no ubuntu@app.homopoluza.ru sudo chown -R www-data /var/www/www.homopoluza.ru/wordpress/ 