---
  rev_proxy:
    hosts:
      homopoluza.ru:
        ansible_host: 51.250.90.79
        ansible_user: "{{ user }}"
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  mysql:
    hosts:
      db01.homopoluza.ru:
        ansible_host: 192.168.10.20
        ansible_user: "{{ user }}"
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ user }}@{{ domain_name }} -o StrictHostKeyChecking=no"'
      db02.homopoluza.ru:
        ansible_host: 192.168.10.30
        ansible_user: "{{ user }}"
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ user }}@{{ domain_name }} -o StrictHostKeyChecking=no"'
  wordpress:
    hosts:
      app.homopoluza.ru:
        ansible_host: 192.168.10.40
        ansible_user: "{{ user }}"
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ user }}@{{ domain_name }} -o StrictHostKeyChecking=no"'
  gitlab:
    hosts:
      gitlab.homopoluza.ru:
        ansible_host: 192.168.10.50
        ansible_user: "{{ user }}"
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ user }}@{{ domain_name }} -o StrictHostKeyChecking=no"'
      runner.homopoluza.ru:
        ansible_host: 192.168.10.60
        ansible_user: "{{ user }}"
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ user }}@{{ domain_name }} -o StrictHostKeyChecking=no"'
  monitoring:
    hosts:
        monitoring.homopoluza.ru:
          ansible_host: 192.168.10.70
          ansible_user: "{{ user }}"
          ansible_ssh_private_key_file: "{{ key_path }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ user }}@{{ domain_name }} -o StrictHostKeyChecking=no"'