---
- name: install mysql
  become: true
  ansible.builtin.apt:
    pkg: 
      - mysql-server
      - mysql-client
    state: present
    update_cache: yes

- name: install pip3
  become: true
  ansible.builtin.apt:
    name: 
      - python3-pip
    state: present

- name: install pymysql
  become: true
  ansible.builtin.pip:
    name: 
      - pymysql
    state: present

- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  become: true

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "password"
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  loop: "{{ mysql.hosts }}"
  become: true
  notify: restart mysql

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: true
  notify: restart mysql

- name: replace config file
  become: true
  ansible.builtin.template:
    src: templates/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql

- name: change server-id for slave
  ansible.builtin.replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: 'server-id = 1'
    replace: 'server-id = 2' 
  when: inventory_hostname == "db02.homopoluza.ru"

- name: create replicator user
  become: true
  community.mysql.mysql_user:
    name: replicator_user
    host: 192.168.10.30
    password: replica_password
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: inventory_hostname == "db01.homopoluza.ru"

- name: setup the slave server to replicate the master server
  become: true
  community.mysql.mysql_replication:
    mode: changeprimary
    master_host: db01.homopoluza.ru
    master_user: replicator_user
    master_password: replica_password
  when: inventory_hostname == "db02.homopoluza.ru"
  notify: restart mysql

- name: create database
  become: true
  community.mysql.mysql_db:
    name: wordpress
    state: present
  when: inventory_hostname == "db01.homopoluza.ru"

- name: create user
  become: true
  community.mysql.mysql_user:
    name: wordpress
    password: wordpress
    priv: "wordpress.*:ALL"
    host: 192.168.10.20
    state: present
  when: inventory_hostname == "db01.homopoluza.ru" 

- name: start replication
  become: true
  community.mysql.mysql_replication:
    mode: startreplica
  when: inventory_hostname == "db02.homopoluza.ru" 