---
servers:
  - fqdn: www.{{ domain_name }}
    ip_add: 192.168.10.40
    port: 80
  - fqdn: gitlab.{{ domain_name }}
    ip_add: 192.168.10.50
    port: 80
  - fqdn: grafana.{{ domain_name }}
    ip_add: 192.168.10.70
    port: 3000 
  - fqdn: prometheus.{{ domain_name }}
    ip_add: 192.168.10.70
    port: 9090
  - fqdn: alertmanager.{{ domain_name }}
    ip_add: 192.168.10.70
    port: 9093