---
- name: install mysql
  become: true
  ansible.builtin.apt:
    pkg: 
      - mysql-server
      - mysql-client
    state: present
    update_cache: yes

- name: replace config file
  become: true
  ansible.builtin.template:
    src: templates/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql

- name: change server-id for slave
  ansible.builtin.replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: 'server-id = 1'
    replace: 'server-id = 2' 
  when: inventory_hostname == db02.{{ domaine_name }}

- name: create replicator user
  community.mysql.mysql_user:
    name: replicator_user
    host: 192.168.10.30
    password: replica_password
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: ansible_hostname == db01.{{ domaine_name }}

- name: setup the slave server to replicate the master server
  community.mysql.mysql_replication:
    mode: changemaster
    master_host: db01.{{ domaine_name }}
    master_user: replicator_user
    master_password: replica_password
  when: ansible_hostname == db02.{{ domaine_name }}
  notify: restart mysql

- name: create database
  community.mysql.mysql_db:
    name: wordpress
    state: present
  when: ansible_hostname == db01.{{ domaine_name }}

- name: create user
  community.mysql.mysql_user:
    name: wordpress
    password: wordpress
    priv: "wordpress.*:ALL"
    host: 192.168.10.20
    state: present
  when: ansible_hostname == db01.{{ domaine_name }}    