---
- name: reload nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: reloaded
    
- name: stop nginx
  become: yes
  ansible.builtin.service:
    name: nginx
    state: stopped